import type { Metadata } from "next";
import { Header } from "./_components/header";
import { Sidebar } from "./_components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoginPage = false;
  return (
    <div className={`min-h-screen flex flex-col bg-neutral-50 `}>
      <Sidebar />
      <div
        className={`min-h-screen flex-1 flex flex-col transition-all duration-300 ${
          !isLoginPage ? "lg:pl-72" : ""
        }`}
      >
        <Header />
        <main className="p-4 md:p-6 flex-1">{children}</main>
      </div>
    </div>
  );
}
